# Generated by Django 6.0.5 on 2026-05-26 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pr_title'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='pr_date_create',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('pr_title', 'pr_description')},
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
